project:
  type: website

website:
  title: "Fabrizio Cariani"
  navbar:
    left:
      # - text: "Home"
      #   href: index.qmd
      - text: "Contact"
        href: contacts.qmd
      - text: "Bio"
        href: bio.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Presentations"
        href: talklog.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Drafts"
        href: drafts.qmd
      - text: "Credits"
        href: credits.qmd
      # - text: "Students"
      #   href: students.qmd
    

format:
  html:
    theme: flatly
    css: styles.css